name: Suggestions for improvement, ideas, or minor bugs
description: Share your feedback or bugs/issues here
title: "[Bug]: "
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the Bug
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction Steps (Optional)
  validations:
    required: false
