name: Bugs (non-major)
description: Report pesky bugs here
title: "[Bug] "
labels: [bug]
body:
- type: textarea
  attributes:
    label: Bug Description
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
  validations:
    required: false
