name: Minor Bug Report
description: Report non-critical/minor bugs
title: "[Bug]: "
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the Bug
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction Steps (Optional)
  validations:
    required: false
