blank_issues_enabled: false
contact_links:
  - name: Bugs, Suggestions, and General Feedback
    url: https://discourse.lol
    about: We’re now tracking all new bug reports and feature suggestions on our Discourse forum.
