openapi: 3.0.0
info:
  version: 1.0.0
  title: OMG.LOL API
servers:
  - url: 'https://alpha.omg.lol/api'
paths:
  /availability:
    get:
      summary: '/availability'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: address
          in: query
          description: 'Address to check'
          required: true
          schema:
            type: string
            example: 'desired-address'
      responses:
        '200':
          description: 'Returns details about the availability of an address'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  code:
                    type: integer
                  address:
                    type: string
                  availability:
                    type: string
                  available:
                    type: boolean
                  message:
                    type: string